dist: bionic
os: linux
language: python
cache: pip npm yarn
addons:
  apt:
    packages:
      - sqlite3
      - libgconf-2-4
install:
  - pip install tox
jobs:
  include:
    - python: 3.6
      name: Linting
      env: TOXENV=lint
      before_script:
        - pip install -U flake8 isort
      script:
        - flake8 src tests setup.py
        - isort -q --recursive --diff src/ tests/
    - name: Wagtail 2.11 & Django 3.1 running on Python 3.8
      python: 3.8
      env: TOXENV=py38-django31-wagtail211
      script: tox -- --nomigrations --reuse-db tests/
    - name: Wagtail 2.12 & Django 3.1 running on Python 3.8
      python: 3.8
      env: TOXENV=py38-django31-wagtail212
      script: tox -- --nomigrations --reuse-db tests/
    - name: Wagtail 2.13 & Django 3.2 running on Python 3.8
      python: 3.8
      env: TOXENV=py38-django32-wagtail213
      script: tox -- --nomigrations --reuse-db tests/
    - name: Wagtail 2.14 & Django 3.2 running on Python 3.9
      python: 3.9
      env: TOXENV=py39-django32-wagtail214
      script: tox -- --nomigrations --reuse-db tests/
    - name: Wagtail 2.15 & Django 4.0 running on Python 3.10
      python: 3.10
      env: TOXENV=py310-django40-wagtail215
      script: tox -- --nomigrations --reuse-db tests/
  allow_failures:
    - python: 3.10
      node_js: 14
      name: End to end test without recording
      env: TOXENV=py38-django32-wagtail214 TEST_GROUP=other
      before_script:
        - yarn install
      script:
        - make test_sandbox &
        - yarn cypress:run
        - kill $(jobs -p) || true
    - python: 3.10
      node_js: 14
      name: End to end test with recording
      env: TOXENV=py38-django32-wagtail214 TEST_GROUP=other
      before_script:
        - yarn install
      script:
        - make test_sandbox &
        - yarn cypress:run --record --key $CYPRESS_KEY
        - kill $(jobs -p) || true
env:
  global:
    - TEST_GROUP=other
    - secure: WnTNkrAWPNWoBhDUH/I8qK+z5z+Tfo9tmC7SC4M1x82kmITnaq+p/thaUUiS53l9WCJftYimUb6ANjwQgI1SYJXDyIcXYpkEShmRChJxyje0KJzbU6o9qBBu/yNm0gG783vCYc74c/SOkSlyTXHdYwFiwap6fv5jS8IJglDrzO2xv9iDODbvpANhlms5z7uArf99ZKF9ykjl0WcBTZTqRPhz4DvWlCeIedG/V6FZhg40Qn8QUYF+5KdlxdHmqlvcrm5ByO1tFS6SXE62tdK+b5mzNexSkswXQnvyYzr9H3oM7NpCspwTv6MocMPh7EN9nHuh+waMdYF6R9kyLYeLgYQAcg6thXEU10b+vJ0ZCqyUFAVgQhPDbDl6W5FAhFwpCr17EYycGKyX+99jyTxbwhTK4YtLOcnSm6ieHsP09FIl+MHDVMxs9CgBYV0TPQocEROtVoDxGxoF7IIp7S1IIun5FoBmwtlSj1BSucxbf95tINRXj841aKb0LOnlL9rmzL3ZY5JcB7S9w+aVD+XU2ZXI2FUWgRxoKHZJXa3VeulNrpfudtdNWILVamqIh1iTjXHlFGNrNYKYv64MdbhKaS/JUQoQ3/C6XyOIDBlejN1BWsjh4yPXEh4L8bf3Xao4GLUqTipswd3jSvEQmGK98+uJev1yI7XOcgNvivy0nB4=
